packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - esbuild
  - msgpackr-extract

confirmModulesPurge: false
allowBuilds:
  esbuild: set this to true or false
  msgpackr-extract: set this to true or false
