export const CONFIG = {
  MAP_SIZE: 100,
  WALK_SPEED: 3.5,
  RUN_SPEED: 6,
  ROTATION_LERP: 0.15,
  CAM_DISTANCE: 14,
  CAM_MIN_ZOOM: 8,
  CAM_MAX_ZOOM: 22,
  CAM_PITCH_DEG: 45,
  CAM_FOV_DEG: 40,
  MOVE_SEND_HZ: 12,
  METEOR_INTERVAL_MIN: 45,
  METEOR_INTERVAL_MAX: 90,
  METEOR_WARNING_LEAD: 3,
  METEOR_FALL_DURATION: 1.75,
  FRAGMENTS_MIN: 4,
  FRAGMENTS_MAX: 6,
  SCATTER_RADIUS_MIN: 3,
  SCATTER_RADIUS_MAX: 8,
  COLLECT_RADIUS: 2,
  FRAGMENT_LIFETIME: 60,
  MAX_PLAYERS: 8,
  PLAYER_RADIUS: 0.55,
  COLLECT_REQUEST_COOLDOWN_MS: 150,
  REMOTE_INTERPOLATION: 0.16,
  NAMEPLATE_HIDE_DISTANCE: 34
} as const;

export const ROOM_NAME = "starfall";

